name: Build HappyOS ISO :)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Tools
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso mkinitcpio coreutils

      - name: Build HappyOS :)
        run: |
          mkdir -p output
          # Rulăm mkarchiso folosind folderul curent ca sursă
          mkarchiso -v -w /tmp/archiso-tmp -o output .

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: HappyOS-ISO
          path: output/*.iso
