name: Build HappyOS ISO :)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y arch-install-scripts squashfs-tools xorriso erofs-utils mtools git

      - name: Install Archiso
        run: |
          git clone https://gitlab.archlinux.org/archlinux/archiso.git
          cd archiso && sudo make install && cd ..

      - name: Fix and Build
        run: |
          # REPARĂM REȚETA (Dacă fișierele sunt rătăcite)
          # Dacă pacman.d e în .github, îl aducem afară
          if [ -d .github/workflows/pacman.d ]; then
            mv .github/workflows/pacman.d ./
          fi
          
          # Creăm foldere obligatorii
          mkdir -p airootfs
          mkdir -p output
          
          # Permisiuni de Root (Obligatoriu pentru Archiso)
          sudo chown -R root:root .
          
          # START BUILD
          sudo mkarchiso -v -w /tmp/archiso-tmp -o output .

      - name: Upload ISO
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HappyOS-ISO
          path: output/*.iso
